In [6]:
from utils import *

# Carregar os dados
X, y = load_data("ocr_car_numbers_rotulado.txt")

# Verificar as dimensões dos dados
print("Dimensões dos dados:", X.shape)
print("Dimensões dos rótulos:", y.shape)

# Redimensionar os dados para imagens 35x35
X = X.reshape(-1, 35, 35)

print("Dimensões das imagens:", X.shape)


Dimensões dos dados: (3352, 1225)
Dimensões dos rótulos: (3352,)
Dimensões das imagens: (3352, 35, 35)


In [7]:
from extractors import *

hog_features = extract_hog_features(X)
print("Dimensões das características HOG:", hog_features.shape)

lbp_features = extract_lbp_features(X)
print("Dimensões das características LBP:", lbp_features.shape)

pca_features = extract_pca_features(X)
print("Dimensões das características PCA:", pca_features.shape)


Dimensões das características HOG: (3352, 324)
Dimensões das características LBP: (3352, 9)
Dimensões das características PCA: (3352, 50)


In [8]:
from classifiers import *

# Avaliar o SVM com características HOG
acc_hog, cm_hog = train_evaluate_svm(hog_features, y)
print("Acurácia SVM com HOG:", acc_hog)
print("Matriz de Confusão SVM com HOG:\n", cm_hog)

# Avaliar o SVM com características LBP
acc_lbp, cm_lbp = train_evaluate_svm(lbp_features, y)
print("Acurácia SVM com LBP:", acc_lbp)
print("Matriz de Confusão SVM com LBP:\n", cm_lbp)

# Avaliar o SVM com características PCA
acc_pca, cm_pca = train_evaluate_svm(pca_features, y)
print("Acurácia SVM com PCA:", acc_pca)
print("Matriz de Confusão SVM com PCA:\n", cm_pca)


Acurácia SVM com HOG: 1.0
Matriz de Confusão SVM com HOG:
 [[67  0  0  0  0  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 58  0  0  0  0  0  0  0]
 [ 0  0  0 81  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0]
 [ 0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  0  0  0 77  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  0]
 [ 0  0  0  0  0  0  0  0 55  0]
 [ 0  0  0  0  0  0  0  0  0 75]]
Acurácia SVM com LBP: 0.10581222056631892
Matriz de Confusão SVM com LBP:
 [[ 0  0  0  0 67  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 58  0  0  0  0  0]
 [ 0  0  0  0 81  0  0  0  0  0]
 [ 0 69  0  0 10  0  0  0  0  0]
 [ 0  0  0  0 62  0  0  0  0  0]
 [ 0  0  0  0 77  0  0  0  0  0]
 [ 0 55  0  0  1  0  0  0  0  0]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0]]
Acurácia SVM com PCA: 1.0
Matriz de Confusão SVM com PCA:
 [[67  0  0  0  0  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 58  0  0  0  0  0  0  0]
 [ 0  0  0 81  0  0  0  0  0  0]
 [ 0  0  0  0

In [9]:
from classifiers import *

# Avaliar o KNN com características HOG
acc_hog_knn, cm_hog_knn = train_evaluate_knn(hog_features, y)
print("Acurácia KNN com HOG:", acc_hog_knn)
print("Matriz de Confusão KNN com HOG:\n", cm_hog_knn)

# Avaliar o KNN com características LBP
acc_lbp_knn, cm_lbp_knn = train_evaluate_knn(lbp_features, y)
print("Acurácia KNN com LBP:", acc_lbp_knn)
print("Matriz de Confusão KNN com LBP:\n", cm_lbp_knn)

# Avaliar o KNN com características PCA
acc_pca_knn, cm_pca_knn = train_evaluate_knn(pca_features, y)
print("Acurácia KNN com PCA:", acc_pca_knn)
print("Matriz de Confusão KNN com PCA:\n", cm_pca_knn)


Acurácia KNN com HOG: 1.0
Matriz de Confusão KNN com HOG:
 [[67  0  0  0  0  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 58  0  0  0  0  0  0  0]
 [ 0  0  0 81  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0]
 [ 0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  0  0  0 77  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  0]
 [ 0  0  0  0  0  0  0  0 55  0]
 [ 0  0  0  0  0  0  0  0  0 75]]
Acurácia KNN com LBP: 0.7839046199701938
Matriz de Confusão KNN com LBP:
 [[54  0  0  0  0  0  8  0  0  5]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 49  9  0  0  0  0  0  0]
 [ 0  0 26 47  0  8  0  0  0  0]
 [ 0  0  0  2 77  0  0  0  0  0]
 [ 1  0  0  7  0 54  0  0  0  0]
 [ 5  0  0  0  0  1 48  0  0 23]
 [ 0  0  1  0  2  0  0 53  0  0]
 [ 0  0  0  0  0  0  0  0 55  0]
 [15  0  0  0  0  0 30  0  2 28]]
Acurácia KNN com PCA: 1.0
Matriz de Confusão KNN com PCA:
 [[67  0  0  0  0  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 58  0  0  0  0  0  0  0]
 [ 0  0  0 81  0  0  0  0  0  0]
 [ 0  0  0  0 

In [10]:
from classifiers import *
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
import numpy as np
# Preparar os dados para a CNN
X_cnn = X.reshape(-1, 35, 35, 1)
y_cnn = to_categorical(y, num_classes=10)

# Dividir os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X_cnn, y_cnn, test_size=0.2, random_state=42)

# Treinar e avaliar a CNN
cnn = build_cnn(input_shape=(35, 35, 1))
cnn.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
loss, acc = cnn.evaluate(X_test, y_test)
y_pred = cnn.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)
cm_cnn = confusion_matrix(y_true, y_pred_classes)

print("Acurácia CNN:", acc)
print("Matriz de Confusão CNN:\n", cm_cnn)


Epoch 1/10


/home/avandocampos/Projects/ppgcc/S1/PDI/T3/env/lib64/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


67/67 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.7028 - loss: 0.9687 - val_accuracy: 1.0000 - val_loss: 0.0075
Epoch 2/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9992 - loss: 0.0147 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 3/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9989 - loss: 0.0164 - val_accuracy: 1.0000 - val_loss: 0.0056
Epoch 4/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9992 - loss: 0.0099 - val_accuracy: 1.0000 - val_loss: 0.0048
Epoch 5/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9996 - loss: 0.0074 - val_accuracy: 1.0000 - val_loss: 0.0053
Epoch 6/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9971 - loss: 0.0227 - val_accuracy: 1.0000 - val_loss: 2.9638e-04
Epoch 7/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9989 - loss: 0.0191 - val_accuracy: 1.0000 - val_loss: 6.7647e-04
Epoch 8/10
67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9968 - loss: 0.0230 - val_accuracy: 1.0000 - val_

In [11]:
from utils import kfold_evaluation

# Definir classificadores
svm_classifier = SVC(kernel='linear')
knn_classifier = KNeighborsClassifier(n_neighbors=3)

# Avaliar SVM com HOG
mean_acc_hog_svm, std_acc_hog_svm, mean_cm_hog_svm = kfold_evaluation(svm_classifier, hog_features, y)
print("Acurácia Média SVM com HOG:", mean_acc_hog_svm)
print("Desvio Padrão SVM com HOG:", std_acc_hog_svm)
print("Matriz de Confusão Média SVM com HOG:\n", mean_cm_hog_svm)

# Avaliar SVM com LBP
mean_acc_lbp_svm, std_acc_lbp_svm, mean_cm_lbp_svm = kfold_evaluation(svm_classifier, lbp_features, y)
print("Acurácia Média SVM com LBP:", mean_acc_lbp_svm)
print("Desvio Padrão SVM com LBP:", std_acc_lbp_svm)
print("Matriz de Confusão Média SVM com LBP:\n", mean_cm_lbp_svm)

# Avaliar SVM com PCA
mean_acc_pca_svm, std_acc_pca_svm, mean_cm_pca_svm = kfold_evaluation(svm_classifier, pca_features, y)
print("Acurácia Média SVM com PCA:", mean_acc_pca_svm)
print("Desvio Padrão SVM com PCA:", std_acc_pca_svm)
print("Matriz de Confusão Média SVM com PCA:\n", mean_cm_pca_svm)

# Avaliar KNN com HOG
mean_acc_hog_knn, std_acc_hog_knn, mean_cm_hog_knn = kfold_evaluation(knn_classifier, hog_features, y)
print("Acurácia Média KNN com HOG:", mean_acc_hog_knn)
print("Desvio Padrão KNN com HOG:", std_acc_hog_knn)
print("Matriz de Confusão Média KNN com HOG:\n", mean_cm_hog_knn)

# Avaliar KNN com LBP
mean_acc_lbp_knn, std_acc_lbp_knn, mean_cm_lbp_knn = kfold_evaluation(knn_classifier, lbp_features, y)
print("Acurácia Média KNN com LBP:", mean_acc_lbp_knn)
print("Desvio Padrão KNN com LBP:", std_acc_lbp_knn)
print("Matriz de Confusão Média KNN com LBP:\n", mean_cm_lbp_knn)

# Avaliar KNN com PCA
mean_acc_pca_knn, std_acc_pca_knn, mean_cm_pca_knn = kfold_evaluation(knn_classifier, pca_features, y)
print("Acurácia Média KNN com PCA:", mean_acc_pca_knn)
print("Desvio Padrão KNN com PCA:", std_acc_pca_knn)
print("Matriz de Confusão Média KNN com PCA:\n", mean_cm_pca_knn)


Acurácia Média SVM com HOG: 0.9991044776119402
Desvio Padrão SVM com HOG: 0.0019113803693829301
Matriz de Confusão Média SVM com HOG:
 [[30.8  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  39.7  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.  31.3  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.1  0.  34.7  0.   0.   0.   0.   0.   0. ]
 [ 0.1  0.   0.   0.  41.2  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.  32.6  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  36.3  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  27.4  0.   0. ]
 [ 0.   0.   0.   0.   0.1  0.   0.   0.  31.2  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  29.7]]
Acurácia Média SVM com LBP: 0.15064854299928926
Desvio Padrão SVM com LBP: 0.05413863229900235
Matriz de Confusão Média SVM com LBP:
 [[ 0.   0.   0.   0.  30.8  0.   0.   0.   0.   0. ]
 [ 0.   9.5  0.   0.  30.2  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  31.3  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  34.8  0.   0.   0. 

In [19]:
from utils import kfold_evaluation_cnn

# Preparar os dados para a CNN
X_cnn = X.reshape(-1, 35, 35, 1)
y_cnn = to_categorical(y, num_classes=10)

# Avaliar a CNN com k-fold cross-validation
mean_acc_cnn, std_acc_cnn, mean_cm_cnn = kfold_evaluation_cnn(X_cnn, y_cnn, k=5, epochs=10)
print("Acurácia Média CNN:", mean_acc_cnn)
print("Desvio Padrão CNN:", std_acc_cnn)
print("Matriz de Confusão Média CNN:\n", mean_cm_cnn)

NameError: name 'build_cnn' is not defined